[package]
name = "relay"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
relay-contracts = { path = "../relay-contracts" }
serde.workspace = true
serde_json.workspace = true
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_System_Pipes"
] }
